### ISSUE TITLE
Diagramas de casos de uso

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#1]
Creación de un diagrama de casos de usos por parejas, para poner en común en la proxima reunión. @martagallegoadan @rosasacedon @sergiocp1997 @aniitadiazm @GuiomarPareja

**Comment by sergiocp1997** [comment]
@Riku97 y yo ya hemos realizado el diagrama de casos de uso para luego ponerlo en común en la próxima reunión.

**Comment by rosasacedon** [comment]
@martagallegoadan y yo también hemos realizado ya nuestro diagrama de casos de uso para la puesta en común del próximo sábado.

**Comment by Riku97** [comment]
Se cierra este issues debido a que ya se encuentra finalizado y completado.

**Comment by Riku97** [comment]
Se cierra este issues debido a que ya se encuentra finalizado y completado.
