### ISSUE TITLE
Fase de implementación de la it3. Codigo en Java

### ISSUE THREAD

**Issue by rosasacedon** [rosasacedon/ISOFT2-2021-BC01#17]

**Comment by aniitadiazm** [comment]
@GuiomarPareja y yo hemos generado ya el código de esta iteracción.

Archivo: https://drive.google.com/drive/folders/1cjH7ayAkvtuFclIkDnEHpc7tzIguLebC?usp=sharing

**Comment by rosasacedon** [comment]
Hoy se ha dado por cerrado la implementación de la iteración 3.

**Comment by Riku97** [comment]
Reabro el issue y lo pongo en in progress debido a que se ha dado por terminada la implementacion, sin subir el codigo correspondiente a github, por favor subsanar ese problema antes de cerrar issues, por favor.

**Comment by aniitadiazm** [comment]
Ya está el problema subsanado, no se había acabado de subir todo y por ello no era visible.
Ya lo tenéis disponible.

**Comment by Riku97** [comment]
Pues cierro el issue y lo doy por terminado.
