### ISSUE TITLE
Fase de implementación de la it2. Codigo en Java

### ISSUE THREAD

**Issue by rosasacedon** [rosasacedon/ISOFT2-2021-BC01#18]

**Comment by rosasacedon** [comment]
Buenas noches chic@s!

@martagallegoadan y @rosasacedon ya hemos dejado subido el código que nos ha generado el propio visual. Los métodos están vacíos y en la próxima entrega los rellenaremos para poder hacer el testing.

**Comment by rosasacedon** [comment]
Esta mañana hemos subido el módulo Maven necesario para luego unificar todo en la rama master. 
Nos queda la funcionalidad de los métodos correspondientes a cada clase.

**Comment by rosasacedon** [comment]
Debemos continuar con la implementación de la iteración 2 porque nos falta pulir un tema de la base de datos. Por eso, este issue va a continuar abierto.

**Comment by rosasacedon** [comment]
Chicos, chicas! Tenemos un problema. @martagallegoadan y yo estamos con el modulo maven de la iteración 2 y no sabemos por qué es como si se nos quedase congelado eclipse. 
Os pongo un ejemplo, estamos escribiendo una línea de código y se nos ha olvidado poner el ";" del final y no nos saltaba error de sintaxis ni nada. 
Nos hemos dado cuenta que la J que aparece en la clase está en blanco en lugar de en azul y no sabemos por qué pero el error puede venir de ahí. 

¿Alguno puede echarnos una mano?

**Comment by martagallegoadan** [comment]
Eso es , estamos teniendo problemas . A ver si alguno puede ayudarnos .Gracias

**Comment by rosasacedon** [comment]
Ya he subido el código a la rama y pese a los problemas que hemos tenido, creo que ya se ha dejado solucionado.

**Comment by Riku97** [comment]
Cierro el issue, ya que se entrego el codigo. Buen trabajo!!
