### ISSUE TITLE
Cambios en diagrama diseño iteracion 1

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#19]
He hecho unos cambios en el diagrama de diseño de la iteracion 1, al darme cuenta de que al generar codigo no funciona como es debido y requeria unos pequeños cambios, solicito poder cambiar de versión

**Comment by rosasacedon** [comment]
Por supuesto 👍

**Comment by Riku97** [comment]
Pues cierro el issue, confirmando que he subido la version 1.0.2 del documento

**Comment by Riku97** [comment]
Abro de nuevo el issue para informar que hemos hecho unos cambios por incongruencias en el codigo y hemos mejorado la version anterior.
