### ISSUE TITLE
Trabajo en iteracion 1

### ISSUE THREAD

**Issue by rosasacedon** [rosasacedon/ISOFT2-2021-BC01#2]
R1 es el primer equipo de trabajo formado por @Riku97 y @sergiocp1997 que tendrán que realizar la fase de requisitos de todo el proyecto general.

**Comment by Riku97** [comment]
@sergiocp1997 y yo hemos realizado la fase de requisitos, se entrega el documento de requisitos en el drive del equipo.

**Comment by rosasacedon** [comment]
Chicos, cuando podais, subid el enlace a la wiki del repo (@sergiocp1997 @Riku97)

**Comment by rosasacedon** [comment]
Ahora @aniitadiazm y #Guiomar realizaran la fase de analisis del it de reservar mesas

**Comment by rosasacedon** [comment]
@martagallegoadan y yo hemos subido la primera versión del diagrama de requisitos y su correspondiente documentación para que entendais lo que hemos hecho y el por qué

**Comment by sergiocp1997** [comment]
> @martagallegoadan y yo hemos subido la primera versión del diagrama de requisitos y su correspondiente documentación para que entendais lo que hemos hecho y el por qué.

**Comment by sergiocp1997** [comment]
> > @martagallegoadan y yo hemos subido la primera versión del diagrama de requisitos y su correspondiente documentación para que entendais lo que hemos hecho y el por qué.

@Riku97 y yo hemos subido la versión 1.0.1 del diagrama de requisitos y su documentación argumentando
