### ISSUE TITLE
Modificacion diagrama de clases it2

### ISSUE THREAD

**Issue by rosasacedon** [rosasacedon/ISOFT2-2021-BC01#20]
Buenos días chicos! Estaba mirando los diagramas del proyecto y me he dado cuenta que habia una serie de inconsistencias a la hora de generar el código de la it2. 
¿Os parece que suba la nueva version?

**Comment by GuiomarPareja** [comment]
He estado revisándolo y me parece bien que hagas la modificación para que puedas generar el código correctamente.

**Comment by Riku97** [comment]
Yo lo he visto y me parece bien el cambio

**Comment by rosasacedon** [comment]
En esta nueva version se ha modificado la relacion que mantenia comanda con platos y bebidas ya que estaban puestas como generalizacion y  es una composicion (1 comanda está formada por 1 o muchos platos y por 1 o muchas bebidas)

Ademas, se ha colocado la clase camarero como abstracta ya que nosotros no vamos a crear un camarero, si no que vamos a crear un camarero_sala y  camarero_barra. Para que las clases que heredan de camarero no sean abstractas, se ha creado un metodo auxiliar, imprimir_recibo(), aunque luego en el codigo que se genere de java, lo relacionemos con el metodo correspondiente en la it4.
