### ISSUE TITLE
Diagramas en un único .vpp

### ISSUE THREAD

**Issue by rosasacedon** [rosasacedon/ISOFT2-2021-BC01#21]
Buenas noches! 

Al hablar con el jefe, nos ha dado el consejo de generar un único archivo vpp para poder tener todo el proyecto en el mismo. Por tanto, he procedido a unir los diagramas de las 3 primeras iteraciones a falta de los diagramas de análisis de la it1 e it3 porque Visual P. me da error a la hora de colocar los boundary, control y entity. También faltan todos los diagramas que se han elaborado en la iteración 4. 

Lo acabo de subir a la carpeta correspondiente en Drive: https://drive.google.com/drive/folders/1MTZotZxrp_YTHBsY_TfF79fQcShUdLFv

**Comment by martagallegoadan** [comment]
Buenas noches , nos hemos equivocado al entender mal al jefe , no es unirlo todo y poner en conjunto todas las interacciones  ,por lo que hemos cambiad de parecer .

**Comment by rosasacedon** [comment]
Como este issue ya no va a ser realizado, lo damos por cerrado. Gracias por tu trabajo @martagallegoadan
