### ISSUE TITLE
Modificación casos de uso iteración 1

### ISSUE THREAD

**Issue by sergiocp1997** [rosasacedon/ISOFT2-2021-BC01#23]
@Riku97 y yo hemos realizado cambios en el diagrama de casos de uso especificando mejor los casos de uso y agrupando todos los casos de uso en el grupo funcional del sistema.
Enlace: https://drive.google.com/drive/u/0/folders/1MTZotZxrp_YTHBsY_TfF79fQcShUdLFv
Damos por cerrado el issue.
@rosasacedon @martagallegoadan @aniitadiazm @GuiomarPareja Por favor mirar y darnos darnos feedback, gracias.

**Comment by Riku97** [comment]
Yo por mi estoy de acuerdo con los cambios y por mi le doy un ok

**Comment by rosasacedon** [comment]
Buenas chicos! He estado mirando el drive y lo veo mucho mejor la verdad. No se nos había ocurrido a ninguno.
Gracias por el trabajo!
Te doy mi ok.

**Comment by Riku97** [comment]
Cierro el issue, debido a que ya estan los cambios realizados

**Comment by Riku97** [comment]
Se ha reabierto debido a un error por parte mia al cerrar el issue, debido a que faltan integrantes por responder

**Comment by martagallegoadan** [comment]
Buenas noches y perdon por las horas , lo he mirado y me parece todo correcto . Gracias

**Comment by aniitadiazm** [comment]
Todo correcto por parte de @GuiomarPareja y yo.
Seguid trabajando!

**Comment by GuiomarPareja** [comment]
Buenas tardes, aunque mi compañera ya dio el OK, dejo reflejado aquí que yo también estoy de acuerdo.
Muchas gracias.

**Comment by martagallegoadan** [comment]
Genial pues como estamos todos de acuerdo , procedo a cerrar este issue
