### ISSUE TITLE
Modificación iteración 4

### ISSUE THREAD

**Issue by martagallegoadan** [rosasacedon/ISOFT2-2021-BC01#26]
Buenas noches , tanto mi compañera @rosasacedon como yo hemos juntado todos los diagramas de la iteración cuatro en un mismo vpp. 
Aquí esta el siguiente enlace:  https://drive.google.com/drive/folders/1zryTP3pVRqTqD5ekXXgQLdFLfhNmB9r2

Gracias .

**Comment by Riku97** [comment]
Me parece perfecto

**Comment by Riku97** [comment]
En la renion de hoy se ha dado el visto bueno a la modificacion de la iteracion 4, por lo que se procede a cerrar este issue.
