### ISSUE TITLE
Modificación iteración 1 

### ISSUE THREAD

**Issue by rosasacedon** [rosasacedon/ISOFT2-2021-BC01#27]
Hola de nuevo chicos y chicas,
@martagallegoadan y yo hemos cambiado el diagrama de casos de uso para poder introducir todos los CdU dentro del sistema. Además hemos estado revisando los CdU por si había alguno propio del sistema y no hemos encontrado ninguno. Igual hemos modificado los métodos que van a tener las interfaces de usuario porque nos hemos dado cuenta que solo debe de llevar el método <<autenticarse(user,pass):boolean>>. 

Cualquier cosa, avisadnos.

**Comment by sergiocp1997** [comment]
Vale chicas buen trabajo.

**Comment by Riku97** [comment]
Vale, me parece perfecto

**Comment by rosasacedon** [comment]
En la reunión de hoy hemos acordado que este trabajo está bien realizado y todos los miembros del equipo están de acuerdo. Por tanto, se procede a cerrar el issue.
