### ISSUE TITLE
Fase de requisitos iteración 5

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#31]

**Comment by Riku97** [comment]
@rosasacedon y @martagallegoadan harán los requisitos de la iteración 5, para el martes 8/12/2020

**Comment by rosasacedon** [comment]
@martagallegoadan y @rosasacedon acabamos de subir a la carpeta Drive los diagramas de requisitos y CdU. 
https://drive.google.com/drive/folders/1hriNNyeagqjLGjtS4mGzPVuZpsQ1rCBO

**Comment by Riku97** [comment]
Perfecto, entonces cierro el issue y lo paso a done
