### ISSUE TITLE
Fase de analisis iteracion 5

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#32]

**Comment by Riku97** [comment]
@GuiomarPareja y @aniitadiazm realizarán la parte de analisis de la iteración 5 para el miercoles 9/12/2020

**Comment by GuiomarPareja** [comment]
@aniitadiazm y yo ya hemos subido nuestro diagrama de análisis.
Nos quedamos a la espera de vuestra respuesta.
Muchas gracias.

**Comment by sergiocp1997** [comment]
Vale chicas buen trabajo.

**Comment by Riku97** [comment]
Perfecto, cierro el issue entonces por haber finalizado vuestro trabajo y lo paso a hecho, buen trabajo chicas, seguid asi!!
