### ISSUE TITLE
Fase de diseño iteracion 5

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#33]

**Comment by Riku97** [comment]
@Riku97 y @sergiocp1997 harán la parte de diseño para el 9/12/2020

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos realizado y subido el archivo .vpp al drive.
Enlace: https://drive.google.com/drive/u/1/folders/1a9xVZsL75ASTEQuya4xMUYGetb3WUw77
Damos por terminado este issue.
@Riku97 cuando puedas ciérralo. Muchas gracias.

**Comment by Riku97** [comment]
Vale, debido a que esta hecho, cierro el issue y lo paso a done
