### ISSUE TITLE
Fase de implementación it1 - Código en java

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#4]
Se publica la implementacion correspondiente con la it1. Nos encargamos @sergiocp1997 Y @Riku97

**Comment by Riku97** [comment]
Se ha subido el codigo generado del visual paradigm y se harán retoques para las dependencias

**Comment by sergiocp1997** [comment]
He subido la segunda versión del código generado del diagrama de clases al repositorio.

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos subido al repositorio los cambios en los paquetes del proyecto que nos recomendó el jefe en la pasada reunión.

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos subido al repositorio los cambios en la clase gestor_jefe_de_sala, en la cual hemos añadido funcionalidad y dependencias. En la clase Mesa también hemos añadido las dependencias para realizar la clase gestor_jefe_de sala. En la clase Estados hemos cambiado los atributos a enumeration. Los cambios se pueden ver en nuestra rama (equipo-de-trabajo-1).

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos subido al repositorio los cambios en el código con la implementación los métodos asignarMesa y asignarCamarero para que nos sirva para el testing del laboratorio y también del segundo trabajo teórico. También hemos hecho cambios en la clase Camarero por Camarero_Sala.

**Comment by Riku97** [comment]
@sergiocp1997 y yo hemos modificado las clases Camarero_Sala y el metodo asignarMesa para que tenga una funcionalidad testeable y creamos 5 camareros_Sala, hasta que haya conexion con la base de datos, lo dejamos para esta noche la base de datos.

**Comment by rosasacedon** [comment]
Genial chicos! Nos basaremos en vuestro código para generar el de la it2 y que no haya inconsistencias con los nombres.

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos cambiado el nombre del archivo BBDD por AgenteBBDD. En dicha clase hemos implementado la funcionalidad del agente, creando y conectando la base de datos y acaban do la funcionalidad del gestor_jefe_sale. Hemos probado los comandos maven y todo funciona correctamente.
@Riku97 cierra cuando puedas.

**Comment by Riku97** [comment]
Se cierra el issue a la 1:20 del 8/12/2020, con unos dias de retraso, debido a la complejitud de la base de datos y sobre todo, a la carga lectiva que teniamos Sergio y yo con respecto a los trabajos de otras asignaturas, disculpad los inconvenientes.
