### ISSUE TITLE
Modificación de la it3 en la fase de diseño.

### ISSUE THREAD

**Issue by aniitadiazm** [rosasacedon/ISOFT2-2021-BC01#40]
@GuiomarPareja y yo hemos realizado una petición de cambio en la fase de diseño de la it3, la cual ha sido aprobada por todos los componentes del equipo en la reunión celebrada hoy.
Los cambios realizados se encuentran en el siguiente enlace al diagrama y se pueden encontrar explicados en la wiki correspondiente a la iteración 3:
https://drive.google.com/file/d/11lmHD_a9edtd5ybEsl9u2lQ8OFUM2aXe/view?usp=sharing

Muchas gracias.

**Comment by GuiomarPareja** [comment]
Muchas gracias @aniitadiazm por subirlo.
Los cambios han sido realizados con motivo de poder adaptar de mejor manera el código de la iteración 3.
