### ISSUE TITLE
implementacion it4

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#42]

**Comment by Riku97** [comment]
La implementacion la hacemos @sergiocp1997 y @Riku97, teniendo que estar para el 19/12/2020.

Nota: el issue se deberia de haber creado el 15/12/2020, pero debido a problemas de disponibilidad no se ha podido hacer.

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos hecho el primer commit con el código generado por el diagrama de clases de diseño .vpp y el agente común.
Se puede comprobar en la rama de trabajo grupo 1.

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos creado la tabla Comida (que contiene la información de los platos) debido a que en la implementación de la iteración 2 no está dicha tabla y hemos tenido que introducir datos ya que nos hemos encontrado la tabla sin ningún dato, con el fin de crear una comando "artificial" ya que no está bien implementado en la iteración 2.

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos creado los métodos getters y setters de las clases que necesitamos y hemos cogido código necesario de las clases ya existentes de iteraciones anteriores y hemos añadido los atributos que requerimos para esta iteración.

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos implementado los métodos solicitar_cuenta y marcar_estados_mesa de la clase Gestor_Camarero_Sala.

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos implementado los métodos obtener_comidas y obtener_bebidas debido a que no podemos acceder a los datos que deberíamos poder obtener.

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos implementado los métodos obtener_comidas debido a que no podemos acceder a los datos que deberíamos poder obtener y las consultas SQL necesarias.

**Comment by Riku97** [comment]
Terminamos de implementar la iteracion 4, cerramos el issue y cumplimos con la planificacion.
