### ISSUE TITLE
Mantenimiento

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#46]
Se tiene que realizar el informe y aqui se dirá el avance y se crearán los correspondientes issues para dar los objetivos del mantenimiento.

**Comment by sergiocp1997** [comment]
@Riku97 , @rosasacedon , @martagallegoadan y yo hemos estado reunidos para generar los informes.

**Comment by Riku97** [comment]
Se ha generado los informes de la iteracion 1, dejando para mañana por la mañana la redaccion de un informe de mantenimiento para adjudicar los issues correspondientes.

**Comment by rosasacedon** [comment]
@sergiocp1997 , @Riku97 y @rosasacedon hemos estado reunidos esta mañana para la redacción del informe de mantenimiento y la adjudicación de los issues correspondientes a cada equipo de trabajo.

**Comment by sergiocp1997** [comment]
Se puede comprobar en este enlace: https://docs.google.com/document/d/1Wg9ts8mSguWzSYia6XDmZCAwTq1X_5CikoGHXsXUcZU/edit?usp=sharing

**Comment by GuiomarPareja** [comment]
Esta mañana, hemos creado una reunión extraordinaria a la que hemos asistido @martagallegoadan , @aniitadiazm y yo.
En ella hemos corregido el error que daba con la iteración 2, del cual no fuimos avisadas, ya que no pudimos asistir a la reunión por motivos personales.
Ya está todo correcto y subido, se puede comprobar en el Git y también en este documento: 

https://docs.google.com/document/d/1Wg9ts8mSguWzSYia6XDmZCAwTq1X_5CikoGHXsXUcZU/edit

Muchas gracias.

**Comment by rosasacedon** [comment]
Debido a que no me encuentro en el grupo de whatsapp y nadie escribió en el issue que generé para que me avisaseis de estas cosas, no me he podido reunir con ellas. Si alguien me hubiese avisado de ello, hubiese estado encantada de poder echar una mano y corregir entre todos ese error. 
De nuevo os ruego que si vais a volver a hacer alguna reunion extraordinaria me aviseis de cualquier forma, bien chat privado en whatsapp o telegram (que teneis mi numero) o bien por el issue de github, incluso por correo electronico (tanto gmail como outlook de la universidad). Gracias!

**Comment by sergiocp1997** [comment]
Hola, debido a que no me encuentro en el grupo de whatsap y que toda comunicación iba a ser por GitHub a mi nadie me ha avisado de que había reunión ni el coordinador ni la secretaria han convocado nada, si hubieran contado conmigo me hubiera conectado y ayudado. Gracias!

**Comment by Riku97** [comment]
Quiero reflejar que se aviso sin tiempo y no se informo a los integrantes @rosasacedon y @sergiocp1997, por lo tanto me gustaría que quedara reflejado en este issue, para que quede constancia de los hechos, tal y como han expresado el resto.

**Comment by sergiocp1997** [comment]
@Riku97 , @rosasacedon y yo ya hemos terminado el mantenimiento de la iteración 1 y 4, todo está reflejado en la rama "mantenimiento" del repositorio y en el drive.
Enlace:  https://docs.google.com/document/d/1Wg9ts8mSguWzSYia6XDmZCAwTq1X_5CikoGHXsXUcZU/edit?usp=sharing

@Riku97 cuando acabes cierra el issue y ponlo a "done". Muchas gracias.

**Comment by aniitadiazm** [comment]
La reunión del día 20 se convocó esa misma tarde para realizarla por la noche, sin consultar. Debido a los 'problemas' que tuvieron con la iteración 3 durante la misma, surge esta reunión que es avisada de la misma forma. Se lo hicimos saber al coordinador, quien creemos que debería haberla convocado para que quien quisiera se conectara.
Hemos realizado un acta extraordinaria ya que se trataba de trabajar de forma oficial sobre el mantenimiento. Debe ser igual de válida que la realizada el día 20 por el resto del grupo. Esperamos que sepáis valorar el trabajo realizado.

Muchas gracias.

**Comment by Riku97** [comment]
Añadir que la reunion que hicimos es una reunion para trabajar que no genero ningun acta, debido a que fue para desarrollar y ayudar al equipo, cierto que fue de sopeton, pero se informo a @martagallegoadan del documento, ya que estabais tambien reunidas y se pasó para que se pudiera añadir lo que fuera conveniente y no se genero acta, para no perjudicar al resto, no fue oficial no se convoco ni nada por mi parte, era adelantar trabajo simple y llanamente, no iba a malas, ni a menospreciar a nadie.

**Comment by GuiomarPareja** [comment]
Aquí te adjunto el enlace al acta que si se generó el día 20 de diciembre: 
https://docs.google.com/document/d/1SnnkEzZgqlVz8GSadRQbmGEjeoVEzP7WzOosU4X7_po/edit

**Comment by Riku97** [comment]
Vale, el problema ya se ha resuelto, ese acta se ha eliminado por equivocación, pido disculpas por el error, no lo vi, quiero pedir, por favor, que se me avise de esos fallos para solventarlos, en vez de tomar acciones unilaterales que errores todos podemos tener. De nuevo, perdon y un saludo.

**Comment by Riku97** [comment]
Al haberse cerrado todos los issues de mantenimiento, se cierra este dando por concluido el mantenimiento.
