### ISSUE TITLE
Mantenimiento Gestor_Jefe_de_Sala it1

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#50]

**Comment by Riku97** [comment]
Se tiene que tener hecho antes de mañana a las 22:00 hora de la reunion extraordinaria, para entregar todo.

**Comment by sergiocp1997** [comment]
@Riku97 y yo hemos realizado el mantenimiento de la iteración 1. Está reflejado en la rama "mantenimiento" del repositorio y en el drive.
Enlace: https://docs.google.com/document/d/1Wg9ts8mSguWzSYia6XDmZCAwTq1X_5CikoGHXsXUcZU/edit?usp=sharing
Procedemos a cerrar el issue.
