### ISSUE TITLE
Mantenimiento Agente_BBDD it1

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#51]

**Comment by Riku97** [comment]
Se tiene que tener hecho antes de mañana a las 22:00 hora de la reunion extraordinaria, para entregar todo.

**Comment by GuiomarPareja** [comment]
@aniitadiazm y yo hemos realizado el mantenimiento del Agente_BBDD de la iteración 1.
Muchas gracias.

**Comment by aniitadiazm** [comment]
Todo ok! Cuando podáis le echáis un ojo

**Comment by Riku97** [comment]
Cierro el issue al haber dado por terminado el matenimiento la pareja asignada.
