### ISSUE TITLE
Mantenimiento Gestor_Camarero_Mesa it4

### ISSUE THREAD

**Issue by Riku97** [rosasacedon/ISOFT2-2021-BC01#52]

**Comment by Riku97** [comment]
Se tiene que tener hecho antes de mañana a las 22:00 hora de la reunion extraordinaria, para entregar todo.

**Comment by rosasacedon** [comment]
Se acaba de modificar uno de los errores de mantenimiento que salían. El error era que en el switch del último método marcar_estado_mesa() faltaba un default.
El código lo subirá @Riku97 junto a las modificaciones de mantenimiento que se han generado de la iteración 1. Todo se subirá a la rama de mantenimiento.

**Comment by rosasacedon** [comment]
Procedo a cerrar el issue.
@Riku97 me ha dado el visto bueno. :)
